/**
 * Official barangays of Quezon City for location dropdowns (Disease Reporting, Sanitation Complaints).
 * Prevents invalid or free-text locations per LGU process.
 */
export const QC_BARANGAYS = [
  "Alicia",
  "Amihan",
  "Apollo",
  "Bagong Lipunan ng Crame",
  "Bagong Pag-asa",
  "Bagong Silangan",
  "Bahay Toro",
  "Balingasa",
  "Balumbato",
  "Batasan Hills",
  "Bayanihan",
  "Blue Ridge",
  "Botocan",
  "Bungad",
  "Camp Aguinaldo",
  "Capri",
  "Central",
  "Claro",
  "Commonwealth",
  "Culiat",
  "Damar",
  "Damayan",
  "Del Monte",
  "Dioquino Zobel",
  "Don Manuel",
  "Doña Aurora",
  "Doña Imelda",
  "Doña Josefa",
  "Duyan-duyan",
  "E. Rodriguez",
  "East Kamias",
  "Escopa",
  "Fairview",
  "Greater Lagro",
  "Gulod",
  "Holy Spirit",
  "Horseshoe",
  "Immaculate Conception",
  "Kaligayahan",
  "Kalusugan",
  "Kamuning",
  "Katipunan",
  "Kaunlaran",
  "Kristong Hari",
  "Krus na Ligas",
  "Laging Handa",
  "Libis",
  "Lourdes",
  "Loyola Heights",
  "Maharlika",
  "Malaya",
  "Mariblo",
  "Marilag",
  "Masagana",
  "Matandang Balara",
  "Milagrosa",
  "Nagkaisang Nayon",
  "Nayon ng Kaunlaran",
  "New Era",
  "North Fairview",
  "Novaliches Proper",
  "Obrero",
  "Old Capitol Site",
  "Paang Bundok",
  "Pag-ibig sa Nayon",
  "Paligsahan",
  "Paltok",
  "Pansol",
  "Paraiso",
  "Pasong Putik",
  "Pasong Tamo",
  "Payatas",
  "Phil-Am",
  "Pinyahan",
  "Project 6",
  "Quirino 3-A",
  "Quirino 3-B",
  "Ramon Magsaysay",
  "Roxas",
  "Sacred Heart",
  "Saint Ignatius",
  "Salvacion",
  "San Agustin",
  "San Antonio",
  "San Bartolome",
  "San Isidro",
  "San Isidro Galas",
  "San Jose",
  "San Martin de Porres",
  "San Roque",
  "Sangandaan",
  "Santa Cruz",
  "Santa Lucia",
  "Santa Monica",
  "Santo Cristo",
  "Santo Domingo",
  "Sauyo",
  "Sienna",
  "Sikatuna Village",
  "Silangan",
  "Socorro",
  "South Triangle",
  "St. Peter",
  "Tandang Sora",
  "Talayan",
  "Talipapa",
  "Tatalon",
  "Teachers Village East",
  "Teachers Village West",
  "Ugong Norte",
  "Unang Sigaw",
  "University of the Philippines Campus",
  "Valencia",
  "Vasra",
  "Veterans Village",
  "Villa Maria Clara",
  "West Kamias",
  "West Triangle",
  "White Plains",
] as const;

export type QCBarangay = (typeof QC_BARANGAYS)[number];

/** Sanitation complaint types for unified sanitation_complaints table (legacy) */
export const SANITATION_COMPLAINT_TYPES = [
  "Garbage accumulation",
  "Illegal dumping",
  "Wastewater leakage",
  "Septic overflow",
  "Drainage blockage",
  "Unsanitary establishments",
] as const;

/** Unified complaint types for Complaints page */
export const COMPLAINT_TYPES = [
  "Wastewater Discharge",
  "Illegal Dumping",
  "Clogged Drainage",
  "Unsanitary Establishment",
  "Garbage in Waterways",
  "Environmental Hazard",
] as const;

export type SanitationComplaintType = (typeof SANITATION_COMPLAINT_TYPES)[number];

/** Quezon City barangay coordinates for disease_cases map (verified cases). */
export const QC_BARANGAY_COORDS: Record<string, [number, number]> = {
  "Commonwealth": [14.6994, 121.0867],
  "Batasan Hills": [14.6819, 121.0968],
  "Holy Spirit": [14.6809, 121.0804],
  "Payatas": [14.7095, 121.1022],
  "Bagong Silangan": [14.6887, 121.1109],
  "Fairview": [14.7131, 121.0690],
  "Novaliches": [14.7283, 121.0439],
  "Tandang Sora": [14.6849, 121.0436],
  "Diliman": [14.6538, 121.0586],
  "Cubao": [14.6180, 121.0579],
  "Kamuning": [14.6316, 121.0437],
  "Project 6": [14.6512, 121.0396],
  "Alicia": [14.6500, 121.0500],
  "Bagong Pag-asa": [14.6600, 121.0400],
  "Bahay Toro": [14.6400, 121.0300],
  "Loyola Heights": [14.6350, 121.0700],
  "University of the Philippines Campus": [14.6538, 121.0586],
};
